# Prefacio {.unnumbered}

> "Nunca el conocimiento había sido tan importante y a la vez tan sospechoso; nunca lo habíamos necesitado tanto y desconfiado al mismo tiempo de él; nunca habíamos depositado tantas esperanzas en el conocimiento como solución mientras se convertía él mismo en un problema" — Daniel Innerarity

ESTA CITA extraída del libro *La sociedad del desconocimiento* [@innerarity2022sociedad] enmarca la paradoja epistemológica a la que se enfrenta nuestra sociedad, y por extensión, el ejercicio del periodismo actual. Esta polarización que nos señala Innerarity es un fenómeno que transciende nuestra fronteras. En una reciente encuesta de Ipsos [@ipsos2023perils] realizada en diez paises, destacan que casi la mitad de la población desconfía de los científicos. A la hora de decidir si un hecho es científicamente verdadero o falso, el 49 % afirma que confía más en su experiencia y en su propia investigación que en las explicaciones de los científicos.

El sociólogo Zygmunt Bauman lo denomina la *modernidad líquida*. Una época que se caracteriza por la fluidez e inestabilidad de las estructuras sociales, incluyendo el conocimiento. El conocimiento deja de ser fijo y acumulativo, transformándose en algo transitorio y efímero, sujeto a cambios constantes y disponible de manera instantánea. Este *conocimiento líquido* ya no se concentra en una verdad sólida o en una autoridad incuestionable, sino que se dispersa en múltiples perspectivas y fuentes fragmentadas, facilitadas por la tecnología y el acceso digital.

Con internet y las redes sociales, el conocimiento se vuelve accesible de inmediato, pero también propenso a cambios constantes. La velocidad de actualización en línea y la proliferación de múltiples fuentes, muchas sin verificación rigurosa, generan un flujo continuo de datos que dificulta distinguir entre información verificada y opiniones o desinformación.  No hay más que abrir Tik Tok, X o Instagram para experimentar la fragmentación de la información y el ritmo vertiginoso al que se genera.  

Ante esta situación, como profesional de la comunicación tienes que armarte con una nueva caja de herramientas que te permita desenvolverse en este mundo *líquido*. Hoy, más que nunca, hay que recuperar la labor de *gatekeeper* del periodismo. Este rol exige tanto seleccionar, filtrar y priorizar la información como contextualizar los hechos y presentarlos de manera sean compresibles para la audiencia. El buen periodismo actúa como filtro necesario entre la realidad líquida y la público.

En mi opinión, el periodismo de datos ofrecen herramientas que ayudan a orientar el debate público en un mundo tan fragmentado. Una de estas herramientas básicas que deberías incorporar a tu caja es la visualización de datos. Es fundamental conocer estas técnicas que permiten expresar argumentos en forma de narrativas visuales. Estas pueden aportar claridad, precisión y profundidad a tus piezas informativas. Comunicar en el siglo XXI pasa por cristalizar la información dispersa y compleja de manera que las audiencias puedan asimilarla sin desorientarse.

Desde que The Guardian lanzara su [Datablog](https://www.theguardian.com/data) en marzo de 2009, las redacciones de las grandes cabeceras de todos los periódicos del mundo han incorporado equipos especializados en periodismos de datos y narrativas visuales. Un ejemplo paradigmático de esta corriente es [John Burn-Murdoch](https://x.com/jburnmurdoch), que empezó contribuyendo al mencionado Datablog, y que actualmente pública en el Financial Times, donde tiene el rol de *chief data reporter*. 

En España, una de las impulsoras del periodismo basado en datos ha sido [Mar Cabra](https://about.me/marcabra), que formó parte del equipo internacional de periodistas que llevó a cabo la investigación de los *Panama papers* (papeles de Panamá) que recibió el Premio Pulitzer 2017. Actualmente, hay grandes equipos de datos en todos los medios importantes siendo un referente el equipo de El Pais liderado por [Kiko Llaneras](https://kiko.llaneras.es/). Me parece interesante señalar otras iniciativas independiente de periodismo de datos como son [Civio](https://civio.es/) y [Datadista](https://www.datadista.com).

La mejor manera de aprender es fijarse y replicar las prácticas de los profesionales con más experiencia. Hay un gran número de excelentes expertos en visualización de datos de los que se puede beber. Ya he citado algunos cuantos de los cuales te recomiendo encarecidamente seguir su trabajo. En estas notas encontrarás gráficos de mis predilectos como [Alberto Cairo](https://www.albertocairo.com/) o [Cole Nussbaumer Knaflic](https://www.storytellingwithdata.com/). También encontrarás ejemplos extraídos de [Pew Research](https://www.pewresearch.org/) y [Our world in data](https://ourworldindata.org/), dos organizaciones de las que te puedes nutrir de información muy relevante presentada de manera extraordinaria.

Espero que estos *primeros pasos* te ayuden a iniciarte en el arte de la visualización de datos y que con ello te animes a adentarte en este fantástico mundo del periodismo de datos. Estaré encantado de recibir tus comentarios y saber si te han sido útiles estas notas en tu práctica profesional.